//! M0 conformance gate: for every reference-encoded fixture, `StreamInfo::scan`
//! must reproduce the fields `wvunpack -ss` reports, and out-of-scope streams
//! must be rejected with the right error.
//!
//! Fixtures were generated by the pinned reference CLI (wavpack 5.9.0 x64);
//! see `tests/fixtures/gen.py`. The `.ss.txt` goldens are that reference's own
//! description of each file, parsed here rather than transcribed by hand, so
//! the expected values cannot drift from what the oracle actually said.

use wavicle::{Error, Scope, StreamInfo};

/// The fields of `wvunpack -ss` output that M0 reproduces.
struct Golden {
    bits: u32,
    is_float: bool,
    channels: u32,
    sample_rate: u32,
    duration: String,
    lossless: bool,
}

fn parse_golden(text: &str) -> Golden {
    let field = |name: &str| -> String {
        text.lines()
            .find(|l| l.starts_with(name))
            .unwrap_or_else(|| panic!("golden missing field {name}"))
            .split_once(':')
            .expect("field has a colon")
            .1
            .trim()
            .to_string()
    };
    // e.g. "16-bit ints at 48000 Hz" / "32-bit floats at 48000 Hz"
    let source = field("source");
    let bits: u32 = source
        .split('-')
        .next()
        .expect("bit depth prefix")
        .parse()
        .expect("numeric bit depth");
    let is_float = source.contains("float");
    let sample_rate: u32 = source
        .rsplit(" at ")
        .next()
        .expect("rate suffix")
        .trim_end_matches(" Hz")
        .parse()
        .expect("numeric rate");
    // e.g. "2 (stereo)" / "1 (mono)"
    let channels: u32 = field("channels")
        .split_whitespace()
        .next()
        .expect("channel count")
        .parse()
        .expect("numeric channels");
    Golden {
        bits,
        is_float,
        channels,
        sample_rate,
        duration: field("duration"),
        lossless: field("modalities").starts_with("lossless"),
    }
}

/// Format frames/rate the way wvunpack renders duration (h:mm:ss.ff).
fn render_duration(frames: u64, rate: u32) -> String {
    // Centiseconds rounded to nearest, matching the reference's rendering
    // (0.1088s -> ".11", 0.4535s -> ".45").
    let rate = u64::from(rate);
    let cs = (frames * 100 + rate / 2) / rate;
    let (h, rem) = (cs / 360_000, cs % 360_000);
    let (m, rem) = (rem / 6_000, rem % 6_000);
    let (s, f) = (rem / 100, rem % 100);
    format!("{h}:{m:02}:{s:02}.{f:02}")
}

fn fixture(name: &str) -> (Vec<u8>, String) {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let wv = std::fs::read(dir.join(format!("{name}.wv"))).expect("fixture .wv");
    let ss = std::fs::read_to_string(dir.join(format!("{name}.ss.txt"))).expect("golden .ss.txt");
    (wv, ss)
}

const LOSSLESS_FIXTURES: &[&str] = &[
    "int16_mono",
    "int16_stereo",
    "int24_stereo",
    "int32_stereo",
    "int32_shifted_mono",
    "f32_mono",
    "f32_stereo",
    "false_stereo",
    "silence_stereo",
    "multiblock_int16_mono",
];

#[test]
fn scan_reproduces_reference_ss_fields_for_every_lossless_fixture() {
    for name in LOSSLESS_FIXTURES {
        let (wv, ss) = fixture(name);
        let golden = parse_golden(&ss);
        let info = StreamInfo::scan(&wv).unwrap_or_else(|e| panic!("{name}: scan failed: {e}"));

        assert_eq!(info.bits_per_sample, golden.bits, "{name}: bits");
        assert_eq!(info.is_float, golden.is_float, "{name}: float");
        assert_eq!(info.channels, golden.channels, "{name}: channels");
        assert_eq!(info.sample_rate, golden.sample_rate, "{name}: rate");
        assert_eq!(info.lossless, golden.lossless, "{name}: modality");
        assert!(info.lossless, "{name}: all these fixtures are lossless");

        let total = info
            .total_samples
            .unwrap_or_else(|| panic!("{name}: first block should declare total samples"));
        assert_eq!(
            render_duration(total, info.sample_rate),
            golden.duration,
            "{name}: duration (total_samples {total})"
        );
        assert_eq!(info.version, 0x410, "{name}: reference stamps 0x410");
    }
}

#[test]
fn multiblock_stream_has_more_than_one_block() {
    let (wv, _) = fixture("multiblock_int16_mono");
    let info = StreamInfo::scan(&wv).expect("scan");
    assert!(
        info.block_count > 1,
        "expected multiple blocks, got {}",
        info.block_count
    );
    // 20000 frames at --blocksize=4096: five blocks.
    assert_eq!(info.total_samples, Some(20000));
}

#[test]
fn single_block_fixtures_scan_as_one_block() {
    let (wv, _) = fixture("int16_stereo");
    assert_eq!(StreamInfo::scan(&wv).expect("scan").block_count, 1);
}

/// M1+M2 gate: our lossless decode must equal `wvunpack -r` output exactly
/// for every integer fixture. The goldens are the reference's own raw decode
/// (native-width little-endian interleaved: 2-byte for 16-bit, 3-byte packed
/// for 24-bit, 4-byte for 32-bit), compared at the typed-sample level.
#[test]
fn decode_matches_reference_raw_output_for_every_int_fixture() {
    let cases: &[(&str, usize)] = &[
        ("int16_mono", 2),
        ("int16_stereo", 2),
        ("false_stereo", 2),
        ("silence_stereo", 2),
        ("multiblock_int16_mono", 2),
        ("int24_stereo", 3),
        ("int32_stereo", 4),
        ("int32_shifted_mono", 4),
    ];
    for &(name, bytes) in cases {
        let (wv, _) = fixture(name);
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
        let golden_bytes =
            std::fs::read(dir.join(format!("{name}.decoded.raw"))).expect("decode golden");
        let golden: Vec<i32> = match bytes {
            2 => golden_bytes
                .chunks_exact(2)
                .map(|b| i32::from(i16::from_le_bytes([b[0], b[1]])))
                .collect(),
            3 => golden_bytes
                .chunks_exact(3)
                .map(|b| i32::from_le_bytes([b[0], b[1], b[2], 0]) << 8 >> 8)
                .collect(),
            4 => golden_bytes
                .chunks_exact(4)
                .map(|b| i32::from_le_bytes([b[0], b[1], b[2], b[3]]))
                .collect(),
            _ => unreachable!(),
        };

        let decoded =
            wavicle::decode_stream(&wv).unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));

        assert_eq!(
            decoded.samples.len(),
            golden.len(),
            "{name}: sample count (ours {} vs reference {})",
            decoded.samples.len(),
            golden.len()
        );
        // Find the first mismatch, if any, for a readable failure.
        if let Some((i, (ours, theirs))) = decoded
            .samples
            .iter()
            .zip(golden.iter())
            .enumerate()
            .find(|(_, (a, b))| a != b)
        {
            panic!("{name}: first mismatch at sample {i}: ours {ours}, reference {theirs}");
        }
    }
}

/// M3 gate: float decode must reproduce the exact 32-bit IEEE-754 pattern of
/// every sample, compared via bit patterns (never float `==`, which is wrong
/// for NaN and signed zero). And the BLAKE3 hash of the decoded f32 bytes must
/// equal the hash of the reference's decoded bytes: the media-identity
/// invariant the consumer keys on.
#[test]
fn float_decode_is_bit_exact_and_blake3_stable() {
    for name in ["f32_mono", "f32_stereo", "f32_specials_mono"] {
        let (wv, _) = fixture(name);
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
        let golden = std::fs::read(dir.join(format!("{name}.decoded.raw"))).expect("golden");

        let decoded =
            wavicle::decode_stream(&wv).unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));
        assert!(decoded.is_float, "{name}: should report float");
        assert_eq!(decoded.bits_per_sample, 32, "{name}: 32-bit");

        // Our samples are IEEE bit patterns as i32; the golden is raw LE f32.
        let ours: Vec<u8> = decoded
            .samples
            .iter()
            .flat_map(|s| (*s as u32).to_le_bytes())
            .collect();
        assert_eq!(ours.len(), golden.len(), "{name}: byte length");

        for (i, (a, b)) in ours
            .chunks_exact(4)
            .zip(golden.chunks_exact(4))
            .enumerate()
        {
            if a != b {
                let ab = u32::from_le_bytes(a.try_into().unwrap());
                let bb = u32::from_le_bytes(b.try_into().unwrap());
                panic!("{name}: sample {i} bits differ: ours {ab:#010x}, reference {bb:#010x}");
            }
        }

        assert_eq!(
            blake3::hash(&ours),
            blake3::hash(&golden),
            "{name}: BLAKE3 identity must survive the round trip"
        );
    }
}

/// M4 gate. For each generated integer buffer: (1) our encode then our decode
/// reproduces the input (self round-trip, runs everywhere), and (2) our encode
/// then the reference `wvunpack -r` reproduces the input, proving a real
/// decoder accepts our stream. The reference leg is skipped when the pinned
/// CLI is not present (the same Layer-0/Layer-1 split as decode).
#[cfg(feature = "encode")]
#[test]
fn encode_round_trips_losslessly_through_ourselves_and_the_reference() {
    use wavicle::{EncodeParams, encode_int};

    fn tone(n: usize, rate: u32, freq: f64, amp: f64, scale: i32) -> Vec<i32> {
        (0..n)
            .map(|i| {
                let s = amp * (2.0 * std::f64::consts::PI * freq * i as f64 / rate as f64).sin();
                (s * scale as f64).round() as i32
            })
            .collect()
    }

    struct Case {
        name: &'static str,
        params: EncodeParams,
        samples: Vec<i32>,
    }
    let p = |channels, sample_rate, bits_per_sample| EncodeParams {
        channels,
        sample_rate,
        bits_per_sample,
    };
    let max16 = (1 << 15) - 1;
    let max24 = (1 << 23) - 1;
    let cases = vec![
        Case { name: "i16 mono tone", params: p(1, 48000, 16), samples: tone(4000, 48000, 220.0, 0.6, max16) },
        Case {
            name: "i16 stereo",
            params: p(2, 44100, 16),
            samples: {
                let l = tone(3000, 44100, 220.0, 0.6, max16);
                let r = tone(3000, 44100, 330.0, 0.5, max16);
                l.iter().zip(&r).flat_map(|(a, b)| [*a, *b]).collect()
            },
        },
        Case { name: "i16 silence", params: p(2, 48000, 16), samples: vec![0; 4000] },
        Case { name: "i16 full scale", params: p(1, 48000, 16), samples: (0..2000).map(|i| if i % 2 == 0 { max16 } else { -max16 - 1 }).collect() },
        Case { name: "i24 stereo", params: p(2, 48000, 24), samples: {
            let l = tone(2000, 48000, 261.0, 0.7, max24);
            let r = tone(2000, 48000, 392.0, 0.4, max24);
            l.iter().zip(&r).flat_map(|(a, b)| [*a, *b]).collect()
        }},
        Case { name: "i32 mono", params: p(1, 48000, 32), samples: tone(2000, 48000, 174.0, 0.5, 1 << 23) },
        Case { name: "i16 ramp mono", params: p(1, 48000, 16), samples: (0..2000).map(|i| ((i as i32 * 17) % 65535) - 32768).collect() },
    ];

    // Locate the pinned reference wvunpack, if present.
    let tool = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testing/wavicle/tools/wvunpack.exe");
    let have_ref = tool.exists();
    let mut ref_checked = 0;

    for case in &cases {
        let wv = encode_int(case.params, &case.samples)
            .unwrap_or_else(|e| panic!("{}: encode failed: {e}", case.name));

        // (1) self round-trip
        let decoded = wavicle::decode_stream(&wv)
            .unwrap_or_else(|e| panic!("{}: self-decode failed: {e}", case.name));
        assert_eq!(
            decoded.samples, case.samples,
            "{}: self round-trip mismatch",
            case.name
        );

        // (2) reference round-trip
        if have_ref {
            let dir = std::env::temp_dir();
            let wv_path = dir.join(format!("wavicle_m4_{}.wv", case.name.replace(' ', "_")));
            let raw_path = dir.join(format!("wavicle_m4_{}.raw", case.name.replace(' ', "_")));
            std::fs::write(&wv_path, &wv).unwrap();
            let status = std::process::Command::new(&tool)
                .args(["-r", "-y", "-q"])
                .arg(&wv_path)
                .arg("-o")
                .arg(&raw_path)
                .status()
                .expect("run wvunpack");
            assert!(status.success(), "{}: wvunpack rejected our stream", case.name);
            let raw = std::fs::read(&raw_path).unwrap();
            let bytes = (case.params.bits_per_sample / 8) as usize;
            let ref_samples: Vec<i32> = raw
                .chunks_exact(bytes)
                .map(|b| match bytes {
                    2 => i32::from(i16::from_le_bytes([b[0], b[1]])),
                    3 => i32::from_le_bytes([b[0], b[1], b[2], 0]) << 8 >> 8,
                    4 => i32::from_le_bytes([b[0], b[1], b[2], b[3]]),
                    _ => unreachable!(),
                })
                .collect();
            assert_eq!(
                ref_samples, case.samples,
                "{}: reference wvunpack round-trip mismatch",
                case.name
            );
            let _ = std::fs::remove_file(&wv_path);
            let _ = std::fs::remove_file(&raw_path);
            ref_checked += 1;
        }
    }

    if have_ref {
        assert_eq!(ref_checked, cases.len(), "all cases should hit the reference");
    } else {
        eprintln!("note: reference wvunpack absent; ran self round-trip only");
    }
}

/// M5 gate. Float encode must round-trip bit-exactly: our encode then our
/// decode reproduces the exact f32 patterns, our encode then the reference
/// `wvunpack -r` reproduces them, and the BLAKE3 of the decoded f32 bytes
/// matches the input's (the media-identity invariant Hocket keys on). Includes
/// the adversarial specials (signed zero, denormals, NaN payloads, infinities).
#[cfg(feature = "encode")]
#[test]
fn float_encode_round_trips_bit_exact_with_blake3_identity() {
    use wavicle::encode_float;

    fn tone(n: usize, rate: u32, freq: f64, amp: f64) -> Vec<f32> {
        (0..n)
            .map(|i| (amp * (2.0 * std::f64::consts::PI * freq * i as f64 / rate as f64).sin()) as f32)
            .collect()
    }

    let specials_bits: [u32; 16] = [
        0x00000000, 0x80000000, 0x3F800000, 0xBF800000, 0x00000001, 0x80000001, 0x007FFFFF,
        0x7F800000, 0xFF800000, 0x7FC00000, 0x7F800001, 0x7FFFFFFF, 0xFFC00000, 0x7F7FFFFF,
        0x00800000, 0x3F000000,
    ];
    let mut specials = Vec::new();
    for _ in 0..16 {
        specials.extend(specials_bits.iter().map(|&b| f32::from_bits(b)));
    }
    specials.extend(tone(240, 48000, 55.0, 0.02));

    struct Case { name: &'static str, channels: u32, rate: u32, samples: Vec<f32> }
    let cases = vec![
        Case { name: "f32 mono", channels: 1, rate: 48000, samples: tone(4000, 48000, 220.0, 0.6) },
        Case {
            name: "f32 stereo",
            channels: 2,
            rate: 48000,
            samples: {
                let l = tone(3000, 48000, 220.0, 0.6);
                let r = tone(3000, 48000, 330.0, 0.5);
                l.iter().zip(&r).flat_map(|(a, b)| [*a, *b]).collect()
            },
        },
        Case { name: "f32 specials", channels: 1, rate: 48000, samples: specials },
        Case { name: "f32 silence", channels: 2, rate: 44100, samples: vec![0.0; 4000] },
    ];

    let tool = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testing/wavicle/tools/wvunpack.exe");
    let have_ref = tool.exists();

    for case in &cases {
        let want_bits: Vec<u32> = case.samples.iter().map(|f| f.to_bits()).collect();
        let wv = encode_float(case.channels, case.rate, &case.samples)
            .unwrap_or_else(|e| panic!("{}: encode failed: {e}", case.name));

        // Self round-trip: decode gives back the exact bit patterns.
        let decoded = wavicle::decode_stream(&wv)
            .unwrap_or_else(|e| panic!("{}: self-decode failed: {e}", case.name));
        assert!(decoded.is_float, "{}: float flag", case.name);
        let got_bits: Vec<u32> = decoded.samples.iter().map(|&s| s as u32).collect();
        for (i, (a, b)) in got_bits.iter().zip(&want_bits).enumerate() {
            assert_eq!(a, b, "{}: self round-trip sample {i}: {a:#010x} vs {b:#010x}", case.name);
        }

        // BLAKE3 identity over the decoded f32 LE bytes.
        let want_bytes: Vec<u8> = want_bits.iter().flat_map(|b| b.to_le_bytes()).collect();
        let got_bytes: Vec<u8> = got_bits.iter().flat_map(|b| b.to_le_bytes()).collect();
        assert_eq!(blake3::hash(&got_bytes), blake3::hash(&want_bytes), "{}: BLAKE3", case.name);

        // Reference round-trip.
        if have_ref {
            let dir = std::env::temp_dir();
            let wv_path = dir.join(format!("wavicle_m5_{}.wv", case.name.replace(' ', "_")));
            let raw_path = dir.join(format!("wavicle_m5_{}.raw", case.name.replace(' ', "_")));
            std::fs::write(&wv_path, &wv).unwrap();
            let status = std::process::Command::new(&tool)
                .args(["-r", "-y", "-q"]).arg(&wv_path).arg("-o").arg(&raw_path)
                .status().expect("run wvunpack");
            assert!(status.success(), "{}: wvunpack rejected our float stream", case.name);
            let raw = std::fs::read(&raw_path).unwrap();
            let ref_bits: Vec<u32> = raw
                .chunks_exact(4)
                .map(|b| u32::from_le_bytes([b[0], b[1], b[2], b[3]]))
                .collect();
            for (i, (a, b)) in ref_bits.iter().zip(&want_bits).enumerate() {
                assert_eq!(a, b, "{}: reference sample {i}: {a:#010x} vs {b:#010x}", case.name);
            }
            let _ = std::fs::remove_file(&wv_path);
            let _ = std::fs::remove_file(&raw_path);
        }
    }
}

/// Multi-block gate. Inputs longer than one block must split into several
/// contiguous blocks that round-trip losslessly through our own decoder and
/// the reference `wvunpack`, for both integer and float.
#[cfg(feature = "encode")]
#[test]
fn long_inputs_split_into_blocks_and_round_trip() {
    use wavicle::{EncodeParams, encode_float, encode_int};

    // ~2.5 blocks at 32768 frames/block.
    let n = 80_000usize;
    let int_samples: Vec<i32> = (0..n)
        .map(|i| ((4000.0 * (i as f64 * 0.02).sin()) as i32))
        .collect();
    let float_samples: Vec<f32> = (0..n)
        .map(|i| (0.6 * (i as f64 * 0.02).sin()) as f32)
        .collect();

    let tool = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testing/wavicle/tools/wvunpack.exe");
    let have_ref = tool.exists();

    let reference_raw = |wv: &[u8], name: &str, bytes: usize| -> Vec<u8> {
        let dir = std::env::temp_dir();
        let wv_path = dir.join(format!("wavicle_mb_{name}.wv"));
        let raw_path = dir.join(format!("wavicle_mb_{name}.raw"));
        std::fs::write(&wv_path, wv).unwrap();
        let ok = std::process::Command::new(&tool)
            .args(["-r", "-y", "-q"]).arg(&wv_path).arg("-o").arg(&raw_path)
            .status().expect("run wvunpack").success();
        assert!(ok, "{name}: wvunpack rejected multi-block stream");
        let raw = std::fs::read(&raw_path).unwrap();
        let _ = std::fs::remove_file(&wv_path);
        let _ = std::fs::remove_file(&raw_path);
        let _ = bytes;
        raw
    };

    // Integer, mono, 16-bit.
    let params = EncodeParams { channels: 1, sample_rate: 48000, bits_per_sample: 16 };
    let wv = encode_int(params, &int_samples).unwrap();
    let info = wavicle::StreamInfo::scan(&wv).unwrap();
    assert!(info.block_count >= 3, "expected multiple blocks, got {}", info.block_count);
    assert_eq!(info.total_samples, Some(n as u64));
    assert_eq!(wavicle::decode_stream(&wv).unwrap().samples, int_samples);
    if have_ref {
        let raw = reference_raw(&wv, "int16", 2);
        let ref_s: Vec<i32> = raw.chunks_exact(2).map(|b| i32::from(i16::from_le_bytes([b[0], b[1]]))).collect();
        assert_eq!(ref_s, int_samples, "int16 multi-block reference mismatch");
    }

    // Float, mono.
    let wv = encode_float(1, 48000, &float_samples).unwrap();
    let info = wavicle::StreamInfo::scan(&wv).unwrap();
    assert!(info.block_count >= 3, "float: expected multiple blocks, got {}", info.block_count);
    let want_bits: Vec<u32> = float_samples.iter().map(|f| f.to_bits()).collect();
    let got_bits: Vec<u32> = wavicle::decode_stream(&wv).unwrap().samples.iter().map(|&s| s as u32).collect();
    assert_eq!(got_bits, want_bits, "float multi-block self round-trip");
    if have_ref {
        let raw = reference_raw(&wv, "f32", 4);
        let ref_bits: Vec<u32> = raw.chunks_exact(4).map(|b| u32::from_le_bytes([b[0], b[1], b[2], b[3]])).collect();
        assert_eq!(ref_bits, want_bits, "float multi-block reference mismatch");
    }
}

/// A non-standard sample rate must round-trip via the ID_SAMPLE_RATE sub-block
/// (header index 0xF), so wavicle is a drop-in for any capture rate.
#[cfg(feature = "encode")]
#[test]
fn non_standard_sample_rate_round_trips() {
    use wavicle::{EncodeParams, encode_float, encode_int};

    let rate = 37_800; // a real but non-table rate (old CD-ROM-XA)
    let ints: Vec<i32> = (0..2000).map(|i| ((3000.0 * (i as f64 * 0.03).sin()) as i32)).collect();
    let wv = encode_int(EncodeParams { channels: 1, sample_rate: rate, bits_per_sample: 16 }, &ints).unwrap();
    let d = wavicle::decode_stream(&wv).unwrap();
    assert_eq!(d.sample_rate, rate, "int: custom rate must survive");
    assert_eq!(d.samples, ints);

    let floats: Vec<f32> = (0..2000).map(|i| (0.5 * (i as f64 * 0.03).sin()) as f32).collect();
    let wv = encode_float(1, rate, &floats).unwrap();
    let d = wavicle::decode_stream(&wv).unwrap();
    assert_eq!(d.sample_rate, rate, "float: custom rate must survive");
    let got: Vec<u32> = d.samples.iter().map(|&s| s as u32).collect();
    let want: Vec<u32> = floats.iter().map(|f| f.to_bits()).collect();
    assert_eq!(got, want);

    // And the reference agrees on the rate.
    let tool = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../testing/wavicle/tools/wvunpack.exe");
    if tool.exists() {
        let dir = std::env::temp_dir();
        let p = dir.join("wavicle_rate.wv");
        std::fs::write(&p, &wv).unwrap();
        let out = std::process::Command::new(&tool).args(["-ss"]).arg(&p).output().unwrap();
        let ss = String::from_utf8_lossy(&out.stdout);
        assert!(ss.contains("37800"), "wvunpack -ss should report 37800 Hz:\n{ss}");
        let _ = std::fs::remove_file(&p);
    }
}

/// A corrupted payload must fail with a CRC error, never decode silently.
#[test]
fn corrupt_audio_fails_the_crc_hard() {
    let (mut wv, _) = fixture("int16_stereo");
    // Flip a bit deep in the block payload (past header + early metadata).
    let target = wv.len() / 2;
    wv[target] ^= 0x10;
    match wavicle::decode_stream(&wv) {
        Err(_) => {}
        Ok(_) => panic!("corrupted stream decoded without error"),
    }
}

#[test]
fn hybrid_stream_is_rejected_as_out_of_scope() {
    let (wv, ss) = fixture("hybrid_lossy_int16_stereo");
    assert!(
        parse_golden(&ss).lossless == false,
        "golden confirms the fixture really is hybrid"
    );
    match StreamInfo::scan(&wv) {
        Err(Error::OutOfScope(Scope::Hybrid)) => {}
        other => panic!("expected OutOfScope(Hybrid), got {other:?}"),
    }
}

#[test]
fn synthetic_headers_reject_bad_version_and_dsd() {
    let (wv, _) = fixture("int16_mono");

    // Version below 0x402 (a pre-4.0 stream).
    let mut old = wv.clone();
    old[8..10].copy_from_slice(&0x310u16.to_le_bytes());
    match StreamInfo::scan(&old) {
        Err(Error::UnsupportedVersion(0x310)) => {}
        other => panic!("expected UnsupportedVersion, got {other:?}"),
    }

    // DSD flag (bit 31 of flags at offset 24).
    let mut dsd = wv.clone();
    dsd[27] |= 0x80;
    match StreamInfo::scan(&dsd) {
        Err(Error::OutOfScope(Scope::Dsd)) => {}
        other => panic!("expected OutOfScope(Dsd), got {other:?}"),
    }

    // Wrong magic.
    let mut junk = wv;
    junk[0] = b'x';
    assert!(matches!(StreamInfo::scan(&junk), Err(Error::BadMagic(_))));
}
