//! M0 conformance gate: for every reference-encoded fixture, `StreamInfo::scan`
//! must reproduce the fields `wvunpack -ss` reports, and out-of-scope streams
//! must be rejected with the right error.
//!
//! Fixtures were generated by the pinned reference CLI (wavpack 5.9.0 x64);
//! see `tests/fixtures/gen.py`. The `.ss.txt` goldens are that reference's own
//! description of each file, parsed here rather than transcribed by hand, so
//! the expected values cannot drift from what the oracle actually said.

use wavicle::{Error, Scope, StreamInfo};

/// The fields of `wvunpack -ss` output that M0 reproduces.
struct Golden {
    bits: u32,
    is_float: bool,
    channels: u32,
    sample_rate: u32,
    duration: String,
    lossless: bool,
}

fn parse_golden(text: &str) -> Golden {
    let field = |name: &str| -> String {
        text.lines()
            .find(|l| l.starts_with(name))
            .unwrap_or_else(|| panic!("golden missing field {name}"))
            .split_once(':')
            .expect("field has a colon")
            .1
            .trim()
            .to_string()
    };
    // e.g. "16-bit ints at 48000 Hz" / "32-bit floats at 48000 Hz"
    let source = field("source");
    let bits: u32 = source
        .split('-')
        .next()
        .expect("bit depth prefix")
        .parse()
        .expect("numeric bit depth");
    let is_float = source.contains("float");
    let sample_rate: u32 = source
        .rsplit(" at ")
        .next()
        .expect("rate suffix")
        .trim_end_matches(" Hz")
        .parse()
        .expect("numeric rate");
    // e.g. "2 (stereo)" / "1 (mono)"
    let channels: u32 = field("channels")
        .split_whitespace()
        .next()
        .expect("channel count")
        .parse()
        .expect("numeric channels");
    Golden {
        bits,
        is_float,
        channels,
        sample_rate,
        duration: field("duration"),
        lossless: field("modalities").starts_with("lossless"),
    }
}

/// Format frames/rate the way wvunpack renders duration (h:mm:ss.ff).
fn render_duration(frames: u64, rate: u32) -> String {
    // Centiseconds rounded to nearest, matching the reference's rendering
    // (0.1088s -> ".11", 0.4535s -> ".45").
    let rate = u64::from(rate);
    let cs = (frames * 100 + rate / 2) / rate;
    let (h, rem) = (cs / 360_000, cs % 360_000);
    let (m, rem) = (rem / 6_000, rem % 6_000);
    let (s, f) = (rem / 100, rem % 100);
    format!("{h}:{m:02}:{s:02}.{f:02}")
}

fn fixture(name: &str) -> (Vec<u8>, String) {
    let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let wv = std::fs::read(dir.join(format!("{name}.wv"))).expect("fixture .wv");
    let ss = std::fs::read_to_string(dir.join(format!("{name}.ss.txt"))).expect("golden .ss.txt");
    (wv, ss)
}

const LOSSLESS_FIXTURES: &[&str] = &[
    "int16_mono",
    "int16_stereo",
    "int24_stereo",
    "int32_stereo",
    "f32_mono",
    "f32_stereo",
    "false_stereo",
    "silence_stereo",
    "multiblock_int16_mono",
];

#[test]
fn scan_reproduces_reference_ss_fields_for_every_lossless_fixture() {
    for name in LOSSLESS_FIXTURES {
        let (wv, ss) = fixture(name);
        let golden = parse_golden(&ss);
        let info = StreamInfo::scan(&wv).unwrap_or_else(|e| panic!("{name}: scan failed: {e}"));

        assert_eq!(info.bits_per_sample, golden.bits, "{name}: bits");
        assert_eq!(info.is_float, golden.is_float, "{name}: float");
        assert_eq!(info.channels, golden.channels, "{name}: channels");
        assert_eq!(info.sample_rate, golden.sample_rate, "{name}: rate");
        assert_eq!(info.lossless, golden.lossless, "{name}: modality");
        assert!(info.lossless, "{name}: all these fixtures are lossless");

        let total = info
            .total_samples
            .unwrap_or_else(|| panic!("{name}: first block should declare total samples"));
        assert_eq!(
            render_duration(total, info.sample_rate),
            golden.duration,
            "{name}: duration (total_samples {total})"
        );
        assert_eq!(info.version, 0x410, "{name}: reference stamps 0x410");
    }
}

#[test]
fn multiblock_stream_has_more_than_one_block() {
    let (wv, _) = fixture("multiblock_int16_mono");
    let info = StreamInfo::scan(&wv).expect("scan");
    assert!(
        info.block_count > 1,
        "expected multiple blocks, got {}",
        info.block_count
    );
    // 20000 frames at --blocksize=4096: five blocks.
    assert_eq!(info.total_samples, Some(20000));
}

#[test]
fn single_block_fixtures_scan_as_one_block() {
    let (wv, _) = fixture("int16_stereo");
    assert_eq!(StreamInfo::scan(&wv).expect("scan").block_count, 1);
}

/// M1 gate: our lossless decode must equal `wvunpack -r` output exactly for
/// every 16-bit fixture. The goldens are the reference's own raw decode
/// (native-width little-endian interleaved), compared at the typed-sample
/// level.
#[test]
fn decode_matches_reference_raw_output_for_every_int16_fixture() {
    let names = [
        "int16_mono",
        "int16_stereo",
        "false_stereo",
        "silence_stereo",
        "multiblock_int16_mono",
    ];
    for name in names {
        let (wv, _) = fixture(name);
        let dir = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
        let golden_bytes =
            std::fs::read(dir.join(format!("{name}.decoded.raw"))).expect("decode golden");
        let golden: Vec<i32> = golden_bytes
            .chunks_exact(2)
            .map(|b| i32::from(i16::from_le_bytes([b[0], b[1]])))
            .collect();

        let decoded =
            wavicle::decode_stream(&wv).unwrap_or_else(|e| panic!("{name}: decode failed: {e}"));

        assert_eq!(
            decoded.samples.len(),
            golden.len(),
            "{name}: sample count (ours {} vs reference {})",
            decoded.samples.len(),
            golden.len()
        );
        // Find the first mismatch, if any, for a readable failure.
        if let Some((i, (ours, theirs))) = decoded
            .samples
            .iter()
            .zip(golden.iter())
            .enumerate()
            .find(|(_, (a, b))| a != b)
        {
            panic!("{name}: first mismatch at sample {i}: ours {ours}, reference {theirs}");
        }
    }
}

/// A corrupted payload must fail with a CRC error, never decode silently.
#[test]
fn corrupt_audio_fails_the_crc_hard() {
    let (mut wv, _) = fixture("int16_stereo");
    // Flip a bit deep in the block payload (past header + early metadata).
    let target = wv.len() / 2;
    wv[target] ^= 0x10;
    match wavicle::decode_stream(&wv) {
        Err(_) => {}
        Ok(_) => panic!("corrupted stream decoded without error"),
    }
}

#[test]
fn hybrid_stream_is_rejected_as_out_of_scope() {
    let (wv, ss) = fixture("hybrid_lossy_int16_stereo");
    assert!(
        parse_golden(&ss).lossless == false,
        "golden confirms the fixture really is hybrid"
    );
    match StreamInfo::scan(&wv) {
        Err(Error::OutOfScope(Scope::Hybrid)) => {}
        other => panic!("expected OutOfScope(Hybrid), got {other:?}"),
    }
}

#[test]
fn synthetic_headers_reject_bad_version_and_dsd() {
    let (wv, _) = fixture("int16_mono");

    // Version below 0x402 (a pre-4.0 stream).
    let mut old = wv.clone();
    old[8..10].copy_from_slice(&0x310u16.to_le_bytes());
    match StreamInfo::scan(&old) {
        Err(Error::UnsupportedVersion(0x310)) => {}
        other => panic!("expected UnsupportedVersion, got {other:?}"),
    }

    // DSD flag (bit 31 of flags at offset 24).
    let mut dsd = wv.clone();
    dsd[27] |= 0x80;
    match StreamInfo::scan(&dsd) {
        Err(Error::OutOfScope(Scope::Dsd)) => {}
        other => panic!("expected OutOfScope(Dsd), got {other:?}"),
    }

    // Wrong magic.
    let mut junk = wv;
    junk[0] = b'x';
    assert!(matches!(StreamInfo::scan(&junk), Err(Error::BadMagic(_))));
}
